package corpus

import "strings"

// fillerWords build readable filler text for source and data files.
var fillerWords = []string{
	"var", "function", "return", "dados", "valor", "lista", "item", "total",
	"config", "usuario", "nome", "data", "if", "else", "for", "null", "true",
	"false", "index", "render", "props", "state", "cliente", "pedido",
}

// filler returns about size bytes of line-structured ASCII text seeded by
// label, ending in a newline.
func filler(label string, size int) []byte {
	p := newPRNG(label)
	var b strings.Builder
	b.Grow(size + 64)
	for b.Len() < size {
		n := 3 + int(p.next()%6)
		for i := range n {
			if i > 0 {
				b.WriteByte(' ')
			}
			b.WriteString(fillerWords[p.next()%uint64(len(fillerWords))])
		}
		b.WriteString(";\n")
	}
	return []byte(b.String())
}

const prefsJS = `# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 */

user_pref("browser.download.dir", "C:\\Documents and Settings\\Joao\\Desktop");
user_pref("browser.startup.homepage", "http://www.google.com.br/");
user_pref("intl.accept_languages", "pt-br,pt,en-us,en");
user_pref("network.cookie.prefsMigrated", true);
`

const bookmarksHTML = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
    <DT><A HREF="http://www.orkut.com/">Orkut</A>
    <DT><A HREF="http://www.ufmg.br/">UFMG</A>
    <DT><A HREF="http://www.baixaki.com.br/">Baixaki</A>
    <DT><A HREF="http://www.fotolog.com/">Fotolog</A>
</DL><p>
`

const winINI = "; for 16-bit app support\r\n[fonts]\r\n[extensions]\r\n[mci extensions]\r\n[files]\r\n[Mail]\r\nMAPI=1\r\n"

const systemINI = "; for 16-bit app support\r\n[386Enh]\r\nwoafont=dosapp.fon\r\nEGA80WOA.FON=EGA80WOA.FON\r\n[drivers]\r\nwave=mmdrv.dll\r\ntimer=timer.drv\r\n"

const hostsFile = "# Copyright (c) 1993-1999 Microsoft Corp.\r\n#\r\n# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.\r\n\r\n127.0.0.1       localhost\r\n"

const desktopINI = "[.ShellClassInfo]\r\nLocalizedResourceName=@%SystemRoot%\\system32\\shell32.dll,-21770\r\nIconResource=%SystemRoot%\\system32\\imageres.dll,-112\r\n"

const senhasTXT = `email: joao.2004@example.com  senha: senha123
orkut: mesma do email
banco: agencia 0000-0  conta 00000-0  senha internet: 0000
wifi casa: CASA / senha: 12345678
`

const leiameUpper = "LEIA-ME\r\n\r\nArquivos copiados do CD de instalacao.\r\n"

const leiameLower = "leia-me\n\nanotacoes soltas, nao apagar.\n"

const vcard = `BEGIN:VCARD
VERSION:2.1
N:Silva;Ana;;;
TEL;CELL:+55 11 0000-0001
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:Souza;Pedro;;;
TEL;CELL:+55 11 0000-0002
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:;Mae;;;
TEL;HOME:+55 11 0000-0003
END:VCARD
`

const indexPHP = `<?php
require_once 'config.php';
require_once 'includes/db.php';
$noticias = buscar_noticias($conexao, 10);
?>
<html>
<head><title>Site do Joao</title><link rel="stylesheet" href="css/estilo.css"></head>
<body>
<img src="img/logo.gif" alt="logo">
<?php foreach ($noticias as $n) { echo "<h2>" . htmlspecialchars($n['titulo']) . "</h2>"; } ?>
</body>
</html>
`

const contatoPHP = `<?php
require_once 'config.php';
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    mail(EMAIL_CONTATO, 'Contato pelo site', $_POST['mensagem']);
    echo 'Mensagem enviada!';
}
?>
<form method="post"><textarea name="mensagem"></textarea><input type="submit"></form>
`

const contatoPHPChanged = `<?php
require_once 'config.php';
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $mensagem = strip_tags($_POST['mensagem']);
    mail(EMAIL_CONTATO, 'Contato pelo site', $mensagem, 'From: site@example.com');
    echo 'Obrigado! Mensagem enviada.';
}
?>
<form method="post"><textarea name="mensagem"></textarea><input type="submit" value="Enviar"></form>
`

const configPHP = `<?php
define('DB_HOST', 'localhost');
define('DB_USER', 'site');
define('DB_PASS', 'site2008');
define('DB_NAME', 'site_antigo');
define('EMAIL_CONTATO', 'contato@example.com');
`

const dbPHP = `<?php
$conexao = mysql_connect(DB_HOST, DB_USER, DB_PASS);
mysql_select_db(DB_NAME, $conexao);

function buscar_noticias($conexao, $limite) {
    $r = mysql_query("SELECT titulo, texto FROM noticias ORDER BY data DESC LIMIT " . (int)$limite, $conexao);
    $lista = array();
    while ($linha = mysql_fetch_assoc($r)) { $lista[] = $linha; }
    return $lista;
}
`

const estiloCSS = "body { font-family: Verdana, sans-serif; background: #eef; }\nh2 { color: #336; }\n"

const gitHEAD = "ref: refs/heads/master\n"

const gitConfig = "[core]\n\trepositoryformatversion = 0\n\tfilemode = false\n\tbare = false\n\tlogallrefupdates = true\n\tsymlinks = false\n\tignorecase = true\n"

const gitDescription = "Unnamed repository; edit this file 'description' to name the repository.\n"

const buildXML = `<?xml version="1.0" encoding="UTF-8"?>
<project name="tcc" default="jar" basedir=".">
  <target name="compile">
    <mkdir dir="bin"/>
    <javac srcdir="src" destdir="bin" source="1.5" target="1.5"/>
  </target>
  <target name="jar" depends="compile">
    <jar destfile="tcc.jar" basedir="bin">
      <manifest><attribute name="Main-Class" value="br.ufmg.tcc.Main"/></manifest>
    </jar>
  </target>
</project>
`

const packageJSON = `{
  "name": "app_react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build"
  }
}
`

const appJS = `import React, { Component } from 'react';
import _ from 'lodash';

class App extends Component {
  render() {
    const itens = _.range(1, 6).map(i => <li key={i}>Item {i}</li>);
    return <div className="App"><h1>Lista de compras</h1><ul>{itens}</ul></div>;
  }
}

export default App;
`

const indexJS = "import React from 'react';\nimport ReactDOM from 'react-dom';\nimport App from './App';\n\nReactDOM.render(<App />, document.getElementById('root'));\n"

const reactIndexHTML = "<!doctype html>\n<html lang=\"pt-br\">\n<head><meta charset=\"utf-8\"><title>App</title></head>\n<body><div id=\"root\"></div></body>\n</html>\n"

const liblistGam = "game \"Counter-Strike\"\nurl_info \"www.counter-strike.net\"\nversion \"1.6\"\nsize \"184000000\"\ngamedll \"dlls\\mp.dll\"\n"

const csConfig = "name \"[BR]Joao\"\nsensitivity \"2.5\"\nbind \"w\" \"+forward\"\nbind \"MOUSE1\" \"+attack\"\nrate \"25000\"\n"

const cueSheet = "FILE \"jogo.bin\" BINARY\r\n  TRACK 01 MODE1/2352\r\n    INDEX 01 00:00:00\r\n"

const emuleLicense = "GNU GENERAL PUBLIC LICENSE\nVersion 2, June 1991\n\nCopyright (C) 1989, 1991 Free Software Foundation, Inc.\n"

const emuleChangelog = "eMule 0.47c\n-----------\n- Fixed a crash in the upload queue\n- Updated Kad\n"

const diarioTXT = "12/03/2011\nHoje foi um dia bom. Ninguem precisa ler isto.\n"

// notasMD is Markdown whose raw HTML must never run in the viewer. Its
// scripts, like those of paginaHTML and desenhoSVG, would set
// __precious_pwned on their window and the top window, which the browser
// tests check.
const notasMD = `# Notas da mudança

Lista do que levar:

- caixas da cozinha
- **documentos** do carro
- [ ] ligar para a transportadora

<script>window.__precious_pwned = true; try { top.__precious_pwned = true } catch (e) {} alert("notas.md executou um script")</script>

<img src="nao-existe.png" onerror="window.__precious_pwned = true; try { top.__precious_pwned = true } catch (e) {} alert('notas.md: onerror')">

` + "```" + `
pacote = "frágil"
` + "```" + `
`

const scriptPY = `#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Renomeia as fotos da câmera pela data."""

import os
import sys


def renomear(pasta):
    for nome in sorted(os.listdir(pasta)):
        if nome.upper().startswith("DSC") and nome.upper().endswith(".JPG"):
            print("renomeando", nome)


if __name__ == "__main__":
    renomear(sys.argv[1] if len(sys.argv) > 1 else ".")
`

// carta1252 is Windows-1252 text: accents plus curly quotes and the euro
// sign, which ISO 8859-1 does not have.
const carta1252 = "Belo Horizonte, 3 de mar\xe7o de 2010\r\n\r\n" +
	"Querida v\xf3,\r\n\r\n" +
	"A viagem para S\xe3o Paulo foi \x93inesquec\xedvel\x94. " +
	"Gastei s\xf3 \x80 50 no caf\xe9 da manh\xe3 \x96 que pre\xe7o!\r\n\r\n" +
	"Beijos, Joao\r\n"

const paginaHTML = `<!doctype html>
<html>
<head><meta charset="utf-8"><title>Página salva</title></head>
<body>
<h1>Página salva do navegador</h1>
<script>window.__precious_pwned = true; try { top.__precious_pwned = true } catch (e) {} document.title = "pagina.html executou um script"; alert("pagina.html");</script>
</body>
</html>
`

const desenhoSVG = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80" viewBox="0 0 120 80">
  <rect x="10" y="10" width="100" height="60" fill="#c33"/>
  <script type="application/ecmascript">window.__precious_pwned = true; try { top.__precious_pwned = true } catch (e) {} alert("desenho.svg executou um script");</script>
</svg>
`

const latin1Name = "Arquivo com nome em Latin-1 (n\xe3o \xe9 UTF-8).\r\n"

// notas2007 is the text inside Documentos/notas_2007.txt.gz.
const notas2007 = `Notas de 2007

- renovar a carteira de motorista em marco
- levar o carro na revisao dos 40 mil
- comprar presente de natal para a Ana
- fazer backup das fotos no DVD antes de formatar o PC
`

// feriasTXT is the deflated text inside Midia/videos.zip.
const feriasTXT = "Video das ferias de 2010, gravado com o celular.\r\n"
